### ISSUE TITLE
Failed to load the meteor-helper package

### ISSUE THREAD

**Issue by zhumangen** [PEM--/meteor-helper#64]
[Enter steps to reproduce:]

1. no responses while logging lots of info using console.log()
2. restart doesn't work.

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Win10-x64
**Thrown From**: [meteor-helper](https://github.com/PEM--/meteor-helper) package 0.29.0

### Stack Trace

Failed to load the meteor-helper package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.e.add (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:155329)
    at measure (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3027445)
    at Package.measure (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3026674)
    at Package.load (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:3027415)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:377113)
    at config.transact (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:375536)
    at Config.transact (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:328072)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:375474)
    at t.loadState.then (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:1:642243)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
language-babel 2.85.0 
language-spacebars 0.3.2 
meteor-api 2.20.0 
meteor-helper 0.29.0 
source-preview 0.5.3 
Stylus 3.2.0 
teletype 0.13.3 
```

**Comment by Angular-Angel** [comment]
I too am having this error. Anyone know if there's been any progreem towards a solution, or at least a work around? :/

**Comment by joeysmart** [comment]
this issue is still alive:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [meteor-helper](https://github.com/PEM--/meteor-helper) package 0.29.0


### Stack Trace

Failed to load the meteor-helper package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.e.add (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:155632)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3015628)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at Package.load (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3015598)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381285)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:380013)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382517)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899185
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
meteor-helper 0.29.0 
```

**Comment by mildswearwords** [comment]
I just tried to add the package to a clean install and am seeing the same issue. Windows 10 machine, Meteor 1.8.3 installed and atom 1.40.1
