### ISSUE TITLE
Failed to load the meteor-helper package again

### ISSUE THREAD

**Issue by joeysmart** [PEM--/meteor-helper#65]
fresh installed atom - added as first package!

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [meteor-helper](https://github.com/PEM--/meteor-helper) package 0.29.0

### Stack Trace

Failed to load the meteor-helper package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.e.add (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:155632)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3015628)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at Package.load (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3015598)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381285)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:380013)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382517)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899185
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
meteor-helper 0.29.0 
```

**Comment by joaomlneto** [comment]
Similar results here, different OS.

Package `meteor-helper` seems to be outdated and no longer maintained.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**Chrome**: 61.0.3163.100
**Node**: v8.9.3
**OS**: MacOS *Mojave* 10.14.5
